### ISSUE TITLE
Download of npm package playwright times out

### ISSUE THREAD

**Issue by korosuke613** [GitHubSecurityLab/actions-permissions#17]
Using the monitor action will fail to download the npm package [playwright](https://github.com/microsoft/playwright). (when `npm ci`)

```
npm ERR! Error: Request to https://playwright.azureedge.net/builds/chromium/1067/chromium-linux.zip timed out after 30000ms
```

https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221

<details>

<summary>Full logs of failed step</summary>

```
##[debug]Evaluating condition for step: 'Install dependencies'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Install dependencies
##[debug]Loading inputs
##[debug]Loading env
Run npm ci
##[debug]/usr/bin/bash -e /home/runner/work/_temp/d439ecb4-d353-4e30-a4ab-5a7[2](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:2)c61e97[3](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:3)3.sh
npm WARN deprecated sorted-array@2.0.[4](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:4): Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm ERR! code 1
npm ERR! path /home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Downloading Chromium 11[5](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:5).0.5790.24 (playwright build v10[6](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:6)[7](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:7)) from https://playwright.azureedge.net/builds/chromium/1067/chromium-linux.zip
npm ERR! Downloading Chromium 115.0.5790.24 (playwright build v1067) from https://playwright-akamai.azureedge.net/builds/chromium/1067/chromium-linux.zip
npm ERR! Downloading Chromium 115.0.5790.24 (playwright build v1067) from https://playwright-verizon.azureedge.net/builds/chromium/1067/chromium-linux.zip
npm ERR! Error: Request to https://playwright.azureedge.net/builds/chromium/1067/chromium-linux.zip timed out after 30000ms
npm ERR!     at ClientRequest.rejectOnTimeout (/home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/utils/network.js:[8](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:8)1:15)
npm ERR!     at Object.onceWrapper (node:events:627:28)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.emitRequestTimeout (node:_http_client:848:[9](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:9))
npm ERR!     at Object.onceWrapper (node:events:627:28)
npm ERR!     at TLSSocket.emit (node:events:525:35)
npm ERR!     at Socket._onTimeout (node:net:570:8)
npm ERR!     at listOnTimeout (node:internal/timers:569:17)
npm ERR!     at process.processTimers (node:internal/timers:512:7)
npm ERR! Error: Request to https://playwright-akamai.azureedge.net/builds/chromium/1067/chromium-linux.zip timed out after 30000ms
npm ERR!     at ClientRequest.rejectOnTimeout (/home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/utils/network.js:81:15)
npm ERR!     at Object.onceWrapper (node:events:627:28)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.emitRequestTimeout (node:_http_client:848:9)
npm ERR!     at Object.onceWrapper (node:events:627:28)
npm ERR!     at TLSSocket.emit (node:events:525:35)
npm ERR!     at Socket._onTimeout (node:net:570:8)
npm ERR!     at listOnTimeout (node:internal/timers:569:17)
npm ERR!     at process.processTimers (node:internal/timers:512:7)
npm ERR! Error: Request to https://playwright-verizon.azureedge.net/builds/chromium/1067/chromium-linux.zip timed out after 30000ms
npm ERR!     at ClientRequest.rejectOnTimeout (/home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/utils/network.js:81:15)
npm ERR!     at Object.onceWrapper (node:events:627:28)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.emitRequestTimeout (node:_http_client:848:9)
npm ERR!     at Object.onceWrapper (node:events:627:28)
npm ERR!     at TLSSocket.emit (node:events:525:35)
npm ERR!     at Socket._onTimeout (node:net:570:8)
npm ERR!     at listOnTimeout (node:internal/timers:569:17)
npm ERR!     at process.processTimers (node:internal/timers:512:7)
npm ERR! /home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/server/registry/index.js:679
npm ERR!       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
npm ERR!             ^
npm ERR! 
npm ERR! Error: Failed to download Chromium 115.0.5790.24 (playwright build v1067), caused by
npm ERR! Error: Download failure, code=1
npm ERR!     at ChildProcess.<anonymous> (/home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/server/registry/browserFetcher.js:95:[16](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:17))
npm ERR!     at ChildProcess.emit (node:events:513:28)
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR!     at /home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/server/registry/index.js:679:13
npm ERR!     at async Registry._downloadExecutable (/home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/server/registry/index.js:678:5)
npm ERR!     at async Registry.install (/home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/server/registry/index.js:627:9)
npm ERR!     at async installBrowsersForNpmInstall (/home/runner/work/homepage-2nd/homepage-2nd/node_modules/playwright-core/lib/server/registry/index.js:8[18](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:19):3)
npm ERR! 
npm ERR! Node.js v18.16.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/[20](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:21)[23](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:24)-07-12T08_14_39_[35](https://github.com/korosuke613/homepage-2nd/actions/runs/5529064180/jobs/10086900069?pr=221#step:5:36)3Z-debug-0.log
Error: Process completed with exit code 1.
##[debug]Finishing: Install dependencies
```

</details>

#### Notes
I have been waiting for a tool like this to come out officially on github! 🤩

- Pull request to add monitor action: https://github.com/korosuke613/homepage-2nd/pull/221
- Target workflow: https://github.com/korosuke613/homepage-2nd/blob/5780552b28697cc933ea237eee214977c28ec9b4/.github/workflows/ci.yaml
- `packages.json`: https://github.com/korosuke613/homepage-2nd/blob/5780552b28697cc933ea237eee214977c28ec9b4/package.json#L61

**Comment by JarLob** [comment]
Should be fixed with f62d32cd684392a758c627a58e0756b734bd54fd. Please reopen if still present.
